- name: Run the Action
  uses: devops-infra/action-pull-request@v0.5.3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    target_branch: main
    reviewer: HiromiShikata
    draft: true
    ignore_users: 'renovate'
